/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.BDcontrol;
import Model.GeneratePdf;
import Control.ValidationsForms;
import Control.OperationsBD;
import Model.Customer;
import Model.Detail;
import Model.Bill;
import Model.Product;
import datechooser.beans.DateChooserCombo;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juani
 */
public class Facturacion extends javax.swing.JFrame {

    /**
     * Creates new form Facturacion
     */
    final BDcontrol BD = new OperationsBD();
    List<Product> products = BD.getProductsDB();
    List<Product> listProducts = new ArrayList<>();
    List<Integer> listAmount = new ArrayList<>();

    public void TablaDeFacturas(List<Bill> bills) {
        //Muestra la tabla con las facturas consultadas
        DefaultTableModel modeloBill = (DefaultTableModel) TablaFacturas.getModel();
        modeloBill.setRowCount(0);

        for (Bill bill : bills) {
            List<Detail> DetailList = BD.getDetailsByInvoiceId(bill.getIdBill());
            int Total = 0;
            for (Detail detail : DetailList) {
                Total += BD.getProductById(detail.getIdProduct()).getPrice() * detail.getAmount();
            }
            modeloBill.addRow(new Object[]{
                bill.getIdBill(),
                BD.getPersonById(bill.getIdPerson()).getIdentificationCard(),
                Total,
                bill.getDate(),
                bill.getState()
            });
            TablaFacturas.setModel(modeloBill);
        }
    }

    public void TableDeProducts() {
        //Adjunta todos los productos a la tabla de productos
        DefaultTableModel modelproduct = (DefaultTableModel) TableProducts.getModel();
        modelproduct.setRowCount(0);
        for (int i = 0; i < listProducts.size(); i++) {
            modelproduct.addRow(new Object[]{
                listProducts.get(i).getName(),
                listAmount.get(i),});
            TableProducts.setModel(modelproduct);
        }
    }

    public Facturacion() {
        // Obtiene todos los productos de la base de datos y los agrega a la comboBox
        initComponents();
        DefaultComboBoxModel<String> shareModel = new DefaultComboBoxModel<>();
        shareModel.addElement("Seleccione...");
        for (Product producto : products) {
            shareModel.addElement(producto.getName());
        }
        ComboProduct.setModel(shareModel);
        List<Bill> bills = BD.getInvoicesDB();
        TablaDeFacturas(bills);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        label8 = new java.awt.Label();
        label12 = new java.awt.Label();
        FechaObj = new datechooser.beans.DateChooserCombo();
        label9 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFacturas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        label22 = new java.awt.Label();
        label24 = new java.awt.Label();
        dateChooserCombo6 = new datechooser.beans.DateChooserCombo();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        Txtidentification = new javax.swing.JTextField();
        ComboProduct = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProducts = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        label28 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        Cantidad = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        label13 = new java.awt.Label();
        ComboFechaMin = new datechooser.beans.DateChooserCombo();
        ComboFechaMax = new datechooser.beans.DateChooserCombo();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setPreferredSize(new java.awt.Dimension(700, 479));
        jPanel4.setLayout(null);

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 204, 255));
        label8.setText("Consulta de facturas ");
        jPanel4.add(label8);
        label8.setBounds(42, 19, 342, 42);

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        label12.setText("Seleccione la fecha que desea consultar");
        jPanel4.add(label12);
        label12.setBounds(52, 71, 457, 31);
        jPanel4.add(FechaObj);
        FechaObj.setBounds(90, 120, 293, 30);

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 204, 255));
        label9.setText("Facturas");
        jPanel4.add(label9);
        label9.setBounds(50, 170, 150, 38);

        TablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "$ Total", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaFacturas);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(90, 220, 670, 259);

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton4.setText("Restart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(650, 120, 100, 30);

        jButton5.setBackground(new java.awt.Color(51, 204, 255));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(390, 120, 100, 30);

        jTabbedPane1.addTab("Consultas", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(907, 785));
        jPanel5.setLayout(null);

        label22.setAlignment(java.awt.Label.CENTER);
        label22.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        label22.setText("Cantidad");
        jPanel5.add(label22);
        label22.setBounds(680, 130, 130, 29);

        label24.setAlignment(java.awt.Label.CENTER);
        label24.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        label24.setText("Fecha de expedición");
        jPanel5.add(label24);
        label24.setBounds(150, 270, 220, 29);
        jPanel5.add(dateChooserCombo6);
        dateChooserCombo6.setBounds(150, 310, 220, 32);

        label25.setAlignment(java.awt.Label.CENTER);
        label25.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label25.setForeground(new java.awt.Color(51, 204, 255));
        label25.setText("Info Factura");
        jPanel5.add(label25);
        label25.setBounds(150, 100, 220, 42);

        label26.setAlignment(java.awt.Label.CENTER);
        label26.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        label26.setText("Número de cédula");
        jPanel5.add(label26);
        label26.setBounds(150, 170, 220, 29);

        label27.setAlignment(java.awt.Label.CENTER);
        label27.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        label27.setText("Producto");
        jPanel5.add(label27);
        label27.setBounds(451, 130, 200, 29);

        Txtidentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtidentificationActionPerformed(evt);
            }
        });
        Txtidentification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtidentificationKeyTyped(evt);
            }
        });
        jPanel5.add(Txtidentification);
        Txtidentification.setBounds(150, 220, 219, 27);

        ComboProduct.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        ComboProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductActionPerformed(evt);
            }
        });
        jPanel5.add(ComboProduct);
        ComboProduct.setBounds(450, 170, 202, 29);

        jButton6.setForeground(new java.awt.Color(51, 204, 255));
        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(820, 170, 30, 30);

        jButton7.setBackground(new java.awt.Color(51, 204, 255));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton7.setText("Generar factura");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(85, 708, 179, 32);

        TableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableProducts);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(450, 220, 400, 170);

        jButton8.setBackground(new java.awt.Color(51, 204, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton8.setText("Generar factura");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(410, 440, 170, 32);

        label28.setAlignment(java.awt.Label.CENTER);
        label28.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label28.setForeground(new java.awt.Color(51, 204, 255));
        label28.setText("Generación de factura");
        jPanel5.add(label28);
        label28.setBounds(0, 20, 990, 42);

        label29.setAlignment(java.awt.Label.CENTER);
        label29.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label29.setForeground(new java.awt.Color(51, 204, 255));
        label29.setText("Productos");
        jPanel5.add(label29);
        label29.setBounds(450, 80, 400, 42);

        label30.setAlignment(java.awt.Label.CENTER);
        label30.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label30.setForeground(new java.awt.Color(51, 204, 255));
        label30.setText("Productos");
        jPanel5.add(label30);
        label30.setBounds(450, 80, 400, 42);

        Cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        Cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cantidad.setEditor(new javax.swing.JSpinner.NumberEditor(Cantidad, ""));
        jPanel5.add(Cantidad);
        Cantidad.setBounds(680, 170, 130, 30);

        jTabbedPane1.addTab("Facturación", jPanel5);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setFont(new java.awt.Font("Berlin Sans FB", 0, 34)); // NOI18N
        label10.setForeground(new java.awt.Color(51, 204, 255));
        label10.setText("Generación de balance por periodo");

        label13.setAlignment(java.awt.Label.CENTER);
        label13.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        label13.setText("Seleccione el rango entre fechas ");

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 204, 255));
        label14.setText("Fecha final");

        label15.setAlignment(java.awt.Label.CENTER);
        label15.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        label15.setForeground(new java.awt.Color(51, 204, 255));
        label15.setText("Fecha inicial");

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboFechaMin, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(label15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboFechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboFechaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboFechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Balance", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //Ingresa la factura a la base de datos y genera el pdf
        String id = Txtidentification.getText();
        String dateInput = dateChooserCombo6.getText();

        
        if (ValidationsForms.isEmpty(id) || ValidationsForms.isEmpty(dateInput)) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese toda la información de la factura para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (TableProducts.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese al menos un producto a la factura para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BDcontrol BD = new OperationsBD();
            Calendar fechaUtil = dateChooserCombo6.getSelectedDate();
            java.util.Date utilDate = fechaUtil.getTime();
            java.sql.Date fechaSQL = new java.sql.Date(utilDate.getTime());
            int ident = Integer.parseInt(id);
            int idCustomer = BD.getIdCustomerByidentification(ident);
            String date = dateInput;

            if (idCustomer == -1) {
                JOptionPane.showMessageDialog(null, "No se ha encontrado al usuario ingresado, por favor registrelo en el sistema", "Usuario no encontrado", JOptionPane.INFORMATION_MESSAGE);
                new RegistroUsuarios().setVisible(true);
            } else {
                //Se crea la factura en la bd
                Bill fct = new Bill(idCustomer, fechaSQL, "pagada");
                int ideFact = BD.addInvoiceDB(fct);

                for (int i = 0; i < listProducts.size(); i++) {
                    //Se ingresan los detalles de la factura a la bd
                    Detail detail = new Detail(listProducts.get(i).getIdProduct(), ideFact, listAmount.get(i));
                    BD.addDetailsDB(detail);
                }
                try {
                    //Se llama la función de GeneratePdf que va a generar el pdf
                    GeneratePdf.genPDF(ideFact, date, ident, products, listAmount);
                } catch (IOException ex) {
                    Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
                }

                JOptionPane.showMessageDialog(null, "Se ha registrado la factura. Se va a mostrar la factura.", "Error", JOptionPane.INFORMATION_MESSAGE);

                try {
                    //Se abre el pdf de la factura creada
                    File path = new File("src\\main\\java\\Bill\\Factura#" + ideFact + ".pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado el archivo solicitado, tal vez ha sido eliminado", "Usuario no encontrado", JOptionPane.INFORMATION_MESSAGE);
                }
                setEmpty();
            }
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        int idPerson = Integer.parseInt(Txtidentification.getText());
        if (BD.getIdCustomerByidentification(idPerson) == null) {
            new RegistroUsuarios().setVisible(true);
        } else {
            Calendar fechaUtil = dateChooserCombo6.getSelectedDate();
            java.util.Date utilDate = fechaUtil.getTime();
            java.sql.Date fechaSQL = new java.sql.Date(utilDate.getTime());
            Bill fct = new Bill(idPerson, fechaSQL, "pagada");
            int idBill = BD.addInvoiceDB(fct);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int Cant = (int) Cantidad.getValue();
        int selection = ComboProduct.getSelectedIndex();
        if (selection != 0) {
            String Product = products.get(selection - 1).getName();
            listAmount.add(Cant);
            listProducts.add(products.get(selection - 1));
            TableDeProducts();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ComboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboProductActionPerformed

    private void TxtidentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtidentificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtidentificationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Consulta el balance en el rango de fechas
        String dateMin = ComboFechaMin.getText();
        String dateMax = ComboFechaMax.getText();
        
        if (ValidationsForms.isEmpty(dateMin) || ValidationsForms.isEmpty(dateMax)) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese las dos fechas para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BDcontrol BD = new OperationsBD();

            Calendar fechaMin = ComboFechaMin.getSelectedDate();
            java.util.Date utilMin = fechaMin.getTime(); // Obtener el java.util.Date directamente
            java.sql.Date Min = new java.sql.Date(utilMin.getTime());

            Calendar fechaMax = ComboFechaMax.getSelectedDate();
            java.util.Date utilDate = fechaMax.getTime(); // Obtener el java.util.Date directamente
            java.sql.Date Max = new java.sql.Date(utilDate.getTime());

            List<Bill> bills = BD.getBalance(Min, Max);
            int Total = 0;
            for (Bill bill : bills) {
                List<Detail> DetailList = BD.getDetailsByInvoiceId(bill.getIdBill());
                for (Detail detail : DetailList) {
                    Total += BD.getProductById(detail.getIdProduct()).getPrice() * detail.getAmount();
                }
            }
            JOptionPane.showMessageDialog(null, "El balance entre " + Min + " y " + Max + " es de: " + Total);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Busca las facturas de x fecha 
        String dateObj = FechaObj.getText();
        if (ValidationsForms.isEmpty(dateObj)) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese una fecha para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            BDcontrol BD = new OperationsBD();
            Calendar fechaUtil = FechaObj.getSelectedDate();
            java.util.Date utilDate = fechaUtil.getTime();
            java.sql.Date fecha = new java.sql.Date(utilDate.getTime());
            TablaDeFacturas(BD.searchInvoicesByDate(fecha));
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        BDcontrol BD = new OperationsBD();
        TablaDeFacturas(BD.getInvoicesDB());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void TxtidentificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtidentificationKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean num = (key >= 48 && key <= 57);
        if (!num) {
            evt.consume();
        }
        if (Txtidentification.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtidentificationKeyTyped

    public void setEmpty() {
        // Vacía los campos de la facturación
        listAmount.clear();
        listProducts.clear();
        TableDeProducts();
        Txtidentification.setText("");
        ComboProduct.setSelectedIndex(0);
        Cantidad.setValue(1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Cantidad;
    private datechooser.beans.DateChooserCombo ComboFechaMax;
    private datechooser.beans.DateChooserCombo ComboFechaMin;
    private javax.swing.JComboBox<String> ComboProduct;
    private datechooser.beans.DateChooserCombo FechaObj;
    private javax.swing.JTable TablaFacturas;
    private javax.swing.JTable TableProducts;
    private javax.swing.JTextField Txtidentification;
    private datechooser.beans.DateChooserCombo dateChooserCombo6;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label22;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
